# Generated by Django 4.2.7 on 2025-06-25 23:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday, 6=Sunday)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField(help_text='Start time for this schedule')),
                ('end_time', models.TimeField(help_text='End time for this schedule')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(help_text='Campaign this schedule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'ordering': ['campaign', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['campaign', 'day_of_week'], name='schedules_campaig_697683_idx'), models.Index(fields=['day_of_week', 'is_active'], name='schedules_day_of__7264cc_idx')],
                'unique_together': {('campaign', 'day_of_week')},
            },
        ),
    ]
