# Generated by Django 4.2.7 on 2025-06-25 23:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent in currency units', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('spend_date', models.DateField(help_text='Date when the spend occurred')),
                ('spend_type', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], default='DAILY', help_text='Type of spend (daily/monthly)', max_length=10)),
                ('description', models.CharField(blank=True, help_text='Optional description of the spend', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(help_text='Campaign that generated this spend', on_delete=django.db.models.deletion.CASCADE, related_name='spends', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Spend',
                'verbose_name_plural': 'Spends',
                'db_table': 'spends',
                'ordering': ['-spend_date', '-created_at'],
                'indexes': [models.Index(fields=['campaign', 'spend_date'], name='spends_campaig_2d41e9_idx'), models.Index(fields=['spend_date'], name='spends_spend_d_e784c7_idx'), models.Index(fields=['spend_type'], name='spends_spend_t_fd78e9_idx')],
            },
        ),
    ]
