# Generated by Django 4.2.7 on 2025-06-25 23:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Campaign name', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused')], default='ACTIVE', help_text='Current campaign status', max_length=20)),
                ('daily_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total spend for current day', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monthly_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total spend for current month', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pause_reason', models.CharField(blank=True, choices=[('DAILY_BUDGET_EXCEEDED', 'Daily Budget Exceeded'), ('MONTHLY_BUDGET_EXCEEDED', 'Monthly Budget Exceeded'), ('OUTSIDE_SCHEDULE', 'Outside Schedule'), ('NO_SCHEDULE', 'No Schedule'), ('MANUAL', 'Manual Pause')], help_text='Reason why campaign was paused', max_length=50, null=True)),
                ('paused_at', models.DateTimeField(blank=True, help_text='When the campaign was paused', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Brand that owns this campaign', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
